version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: user_service_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_service_production
    networks:
      - app_network

  web:
    build: .
    container_name: user_service
    depends_on:
      - vite
      - db
    entrypoint: ./docker-rails.sh
    environment:
      RAILS_ENV: development
      VITE_RUBY_HOST: vite
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: user_service_development
      DATABASE_HOST: db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - app_network

  vite:
    build: .
    command: ./docker-vite.sh
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - "3036:3036"
    volumes:
      - .:/app
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: user_service_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./config/ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: