default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: <%= ENV.fetch("PG_PASSWORD") %>

development:
  <<: *default
  database: user_service_development

test:
  <<: *default
  database: user_service_test

production:
  <<: *default
  database: user_service_production